FROM golang:1.22 AS builder

WORKDIR /go/src/practice-4
COPY . .

RUN go mod download
RUN go test ./...

FROM alpine:latest

COPY --from=builder /go/src/practice-4 /app

WORKDIR /app
CMD ["go", "test", "./..."]
